source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-strong-params', git: 'git@github.com:evanleck/sinatra-strong-params.git'
gem 'tilt-jbuilder', '>= 0.4.0'
gem 'thin'
gem 'sinatra-activerecord'
gem 'mysql2'
gem 'rake'
gem 'httparty'